version: '3'

services:
  db:
    container_name: 'jv-db'
    image: 'postgres:13'
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
  db-admin:
    container_name: jv-dbadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - '8080:80'
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-servers:/pgadmin4/servers.json
  graphql:
    container_name: jv-graphql
    build: ./graphql
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - 5433:5433
    restart: always
    volumes:
      - ${PERU_INSPECTIONS_DIRECTORY}:/peru-departure-inspections
      - ${CHILE_INSPECTIONS_DIRECTORY}:/chile-departure-inspections
  server:
    container_name: 'jv-server'
    build: ./server
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - '3001:3001'
    restart: always
    volumes:
      - ./server:/server
      - server_nodemodules:/server/node_modules
      - ${PERU_INSPECTIONS_DIRECTORY}:/server/static/peru-departure-inspections
      - ${CHILE_INSPECTIONS_DIRECTORY}:/server/static/chile-departure-inspections
  inspections-service:
    container_name: 'jv-inspections-service'
    build: ./inspections-service
    depends_on:
      - db
      - graphql
    env_file:
      - ./.env
    ports:
      - '3002:3002'
    restart: always
    volumes:
      - ./inspections-service:/inspections-service
      - inspections-service_nodemodules:/inspections-service/node_modules
      - ${CHILE_INSPECTIONS_DIRECTORY}:/chile-departure-inspections
      - ${PERU_INSPECTIONS_DIRECTORY}:/peru-departure-inspections
  client:
    container_name: 'jv-client'
    build: ./client
    depends_on:
      - db
      - graphql
      - server
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./client:/client
      - client_nodemodules:/client/node_modules

volumes:
  db-data:
  pgadmin-data:
  pgadmin-servers:
  inspections-service_nodemodules:
  client_nodemodules:
  server_nodemodules:
